name: Deploy backend API to AWS ECS

on:
  push:
    paths:
      - 'backend/**'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          java-version: '23'
          
      - name: Build Spring Boot app
        run: |
          ./mvnw clean package -DskipTests

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY_URI }}:latest .

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.ECR_REPOSITORY_URI }}:latest

      - name: Update ECS service
        uses: jakejarvis/ecs-deploy-action@v2
        with:
          cluster: ${{ secrets.CLUSTER_NAME }}
          service: ${{ secrets.SERVICE_NAME }}
          task-definition: ${{ secrets.ECR_REPOSITORY_URI }}:latest
          region: ${{ secrets.AWS_REGION }}
          image: ${{ secrets.ECR_REPOSITORY_URI }}:latest
